# This file contains values from Cookiecutter

default_context:
  project_name: "adaptive_filter"
  project_description: "Python implementation of DSP adaptive filters"
  organization: "bglid"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "bglid"
  email: "benjamin.h.glidden@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
